### ISSUE TITLE
Provide a Rules Schema Registry

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#10]
1. Create a small service Schema Registry Service
 2. CRUD and Search on Schema Object
 3. Schema object properties
    a. id
    b. schema txt
    c. name
    d. description
    e. type
 4. Token based Authorization (header includes bearer token)
 5. Backend Storage HSQLDB
 6. Supported Scheam types
    a. Velocity templates
    b. Protobuf
    c. Avro
7. UI
    a. In the add Kafka Plugin Action diagalog allow Tenant user choose existing Velocity Template from a or add a new Velocity Template
    b. Add Schema Registry to the In the Tenant Admin screens that provides a table view to allow CRUD actions.

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#7

**Comment by niaalex** [comment]
We are no longer doing this.
