### ISSUE TITLE
SPIKE: Migration tool and strategy

### ISSUE THREAD

**Issue by XxChauhanxX** [hashmapinc/Tempus#1012]
Child of #556
This card is to do a spike on the overall migration strategy along with the analysis of Tools which could be used for the Angular upgrade and migration. 

At the end of the SPIKE we should be ready with the strategy to migrate from current Angular version to Angular 7. 
A decision log should also be maintained keeping a track on the decisions behind choosing one Tool/strategy over the other.

**Comment by Shobhit2884** [comment]
Angular 1.6 to Angular upgrade :-

UpgradeModule ngUpgrade Module can be used for upgrading the Angular 1.6 to Angular 7
When using ngUpgrade module we can run running both AngularJS and Angular at the same time as hybrid applications.
 
There are some prerequisite for application to be upgraded using ngUpgrade:-

1).There are a few rules in particular that will make it much easier to do an incremental upgrade using the Angular upgrade/static module:

2).The Rule of 1 states that there should be one component per file. This not only makes components easy to navigate and find, but will also allow us to migrate them between languages and frameworks one at a time. In this example application, each controller, component, service, and filter is in its own source file.

Following are the articles which provide more details :-

1).https://angular.io/guide/upgrade
2).https://medium.com/sv-blog/running-angularjs-1-6-in-angular-5-side-by-side-d2ed771e2a8f
