### ISSUE TITLE
Analysis on the Current dashboard implementation

### ISSUE THREAD

**Issue by XxChauhanxX** [hashmapinc/Tempus#1046]
Child of #556
The analysis of the current implementation would give insights on the current implementation and a way forward to create the new implementation for the new dashboard.

**Comment by shgupta22** [comment]
The current implementation of the Dashboard store the complete information in JSON format. Whenever we create a Dashboard on UI a JSON will be created. On the backend, it will be stored in a single column of dashboard table named "_configuration_". To render a dashboard on UI the complete JSON is fetched from backend and then it is parsed on the frontend in plain javascript code.

Dashboard configuration JSON details:
- **widgets**: contains details about all the widgets configured in dashboard. It also contain the data source information, positioning details and some widget related properties
- **states**: define the complete layout of the dashboard. It has widgets id with its coordinate and row and column position. 
- **entityAliases**: contains the details of data sources, with entity type, entity id from which data needs to be fetched
- **timeWindow**: defines the time window for which historical telemetry data need to be fetched from backend
-**depthWindow**: defines the depth window for which historical depthseries data need to be fetched from backend
- **setting**: these are the configurations related to the dashboard, like what will be the background color of the dashboard, size of the dashboard, top and left margin etc
