### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#166]
Right click or add a button on a device and be able to export all data to csv file. the data would either be attributes, time series, or (if enabled depth series). The user would have to choose which dataset to export.

The service will be a rest service inside of tempus, it will expose an API in the same pattern as the other services. The data will have to be pivoted for time series and depth series, the attributes can be output in columnar form. The data for time series and depth series will be pivoted on time, such that time is in the first column, and each mnemonic is another column with the values representing the rows:

|TS     |Key 1 | Key 2 | Key 3
|t1.    | 1.2      | 3.3    | 4.4

etc...

If after pivoting, not all the values are time aligned (meaning for time Tx you do not have a value for Key 2, leave it empty (i.e, no value just a comma immediately following the previous comma)

The tables it will read from are:

For Attributes:
Table: ATTRIBUTE_KV 
Columns: LAST_UPDATE_TS, ATTRIBUTE_KEY, and Depending on type a value column

For Time series:
Table: TS_KV
Columns: TS, KEY1, Key2, Key3, ...

For Time series:
Table: DS_KV
Columns: TS, KEY1, Key2, Key3, ...

**Comment by jetinder20** [comment]
Required changes are on branch - tempus-42-Export_CSV

Also the service accepts startTS/StartDs and endTS/endDs to limit the data to download.
