### ISSUE TITLE
Support for json deviceType format for application creator

### ISSUE THREAD

**Issue by ganeshx** [hashmapinc/Tempus#178]

**Comment by jetinder20** [comment]
The JSON which needs to be supported for device types has following structure

deviceTypes: [{name:"device1"}, {name: "device2"}]

**Comment by ganeshx** [comment]
For description, add the JSON structure as follows.

{
    " additionalInfo": {
          "description": "string"
     }
}

**Comment by jetinder20** [comment]
Changes committed to branch  Tempus-116-deviceTypes.
