### ISSUE TITLE
Users should be able to create and edit dashboards

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#190]
Users should be able to create and edit dashboards. Upon save, if not already, the dashboard should be assigned to the customer that the client is a part of.

**Comment by VikashSingh94** [comment]
At the time of creation of dashboard only its name is taken,  So is it that the assigning to customer feature should also be there?

**Comment by cherrera2001** [comment]
users should be able to create dashboards. If a user creates a dashboard it should be auto-assigned to the customer that a user is in
