### ISSUE TITLE
Add the service to save the configuration for tempusboard devicetypes

### ISSUE THREAD

**Issue by ganeshx** [hashmapinc/Tempus#203]

**Comment by jetinder20** [comment]
I will work on providing a service which will be generic and can be used in future for any other flows if need be. 

The contract of service is just key/value pair and its the responsibility of user of API to provide a unique key and a value for each use case. The service will provide all CRUD operations.

**Comment by jetinder20** [comment]
Changes have been pushed to Tempus-72-tempusboard-settings branch. Ganesh will raise a PR once he is done with UI integration.

Also, for existing customer Concho we will have to execute the queries manually while we upgrade for them. Here are the queries to do it (some queries will change depending on the values in table admin_settings)


CREATE TABLE IF NOT EXISTS tempus.user_settings (id timeuuid , key text, json_value text, user_id timeuuid, PRIMARY KEY (id, user_id ));


[This query will change according the values in admin_settings table]
INSERT INTO tempus.user_settings (id, key, json_value, user_id) values (121f5c10-4970-11e8-8359-19e0d0b8c61f, 'mail', '{"mailFrom":"tempus <sysadmin@localhost.localdomain>","smtpProtocol":"smtp","smtpHost":"localhost","smtpPort":"25","timeout":"10000","enableTls":"false","username":"","password":""}', 11ff7800-4970-11e8-8359-19e0d0b8c61f);

[This query will change according the values in admin_settings table]
INSERT INTO tempus.user_settings (id, key, json_value, user_id) values (121dfc80-4970-11e8-8359-19e0d0b8c61f, 'general', '{"baseUrl":"http://localhost:8080"}', 11ff7800-4970-11e8-8359-19e0d0b8c61f);





CREATE MATERIALIZED VIEW IF NOT EXISTS tempus.user_settings_by_key AS
  SELECT * FROM tempus.user_settings WHERE key IS NOT NULL AND id IS NOT NULL AND user_id IS NOT NULL PRIMARY KEY (user_id, key, id ) WITH CLUSTERING ORDER BY ( id DESC );  


drop MATERIALIZED VIEW tempus.admin_settings_by_key;
drop TABLE tempus.admin_settings;
