### ISSUE TITLE
Create a new User Type of SYSTEM

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#235]

**Comment by cherrera2001** [comment]
In order to facilitate the use of an external micro service, this service will have to communicate with Tempus via a special user type of SYSTEM. 

This will be essentially a new authority type in Tempus. This user CANNOT access tempus via the UI, only the Rest API only. The user will have special access to modify the metadata api tables at the moment via add and update.

**Comment by jetinder20** [comment]
Did the analysis in this one and It will be covered in 362.
