### ISSUE TITLE
Provide a service to attach a computation to Application

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#27]
_From @jetinder20 on January 30, 2018 6:37_

null

_Copied from original issue: hashmapinc/Timeseries#151_

**Comment by cherrera2001** [comment]
_From @jetinder20 on January 30, 2018 6:40_

This also includes providing the service to invalidate an application when attached computation is deleted. However, that service needs to be plugged in computation delete flow.

**Comment by jetinder20** [comment]
The Service to invalidate an Application is already there. I will work with Jay/Himanshu to plug that in computation delete flow when its ready.

**Comment by jetinder20** [comment]
The service has been plugged in.
