### ISSUE TITLE
Tempusboard not showing mini dashboard

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#373]
When configured no minidashboard appears for tempus board.

**Comment by cherrera2001** [comment]
It seems after further debugging the application is reporting as invalid, this should not be the case as all dependancies are started and running correctly.

**Comment by jetinder20** [comment]
As discussed, the issue was because of different cases  used for device type when saved and queried for application. The issue has already been fixed by @ganeshx  on a different branch. We can close this one @cherrera2001.
