### ISSUE TITLE
There is an issue on the login page of tempus that is causing styling issues

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#400]
Child of #309 

When a user navigates to https://tempus.hashmapinc.com, they are presented with an error and an incorrectly styled screen: 

There is an error present that reads:
Unconfigured table theme.

**Comment by Shobhit2884** [comment]
Hi Chris,

  What i found is that the table is not able to be created on the
environment.Can you please send me the details of the environment so that
we can check the logs for this.


Thanks and Regards,
Shobhit Sharma
