### ISSUE TITLE
Create Tempus as a Resource server for Oauth2

### ISSUE THREAD

**Issue by jayeshkapadnis** [hashmapinc/Tempus#415]
Child of #414

**Comment by jetinder20** [comment]
Code changes are committed on branch "414_HAF_Authentication_Server_integration". 

Not raising a PR yet, as I will be working further on this branch to make more changes for HAF authorization server and hence can't be merged yet.

Needs a review from Jayesh.

**Comment by jayeshkapadnis** [comment]
Looks good to me.
Few suggestions:
1. For resource server you either have to configure userInfoUri or tokenInfoUri not both.
2. I can see you removed Token parsing logic from your code, just to give you background it is not necessary when you are just checking for Authority as we have done in Tempus also it's not necessary to do authorization based on claims added in token as we are going to build it for ABAC scheme. You need it when you want to construct a principal (User) and need to authorize based on user attributes say tenantId. Where on controller you say @PreAuthorize('subject.tenantId == resource.tenantId'). We will do those changes when we duplicate User models from HAF to Tempus and Add Complex ABAC rules.
