### ISSUE TITLE
Create a Tempus QA cluster

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#456]
Child of #814
Currently there is only one cluster -- demo ("prod") we need to have a QA cluster for quick tests intra-sprint.

This cluster will require only 1 t2.medium master and 2 t2.medium nodes. There will be RBAC enabled on this cluster to mirror prod.

**Comment by SPParnerkar** [comment]
QA cluster was created but we need to move into a single AWS instance for better manageability.
