### ISSUE TITLE
Configure authorization from Jenkins to Github

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#458]
Configure OAuth 2 so that Jenkins will use GitHub for authentication and authorization.

**Comment by SPParnerkar** [comment]
Created OAuth Application, configured Jenkins SecurityDomain to use Github Auth, Able to direct login request to Github OAuth app but login fails on callback URL.

**Comment by SPParnerkar** [comment]
Issue fixed by Chris. Working fine.
