### ISSUE TITLE
Configure a Jenkins Pipeline to build Tempus

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#459]
There needs to be a Jenkins pipeline, that is triggered off of a commit to dev, to build, run tests, and create a docker image and push it to docker hub.

**Comment by SPParnerkar** [comment]
Chris,

Can you please attach Jenkinsfile and/or any other artefact you have with respect to this and #459. I will review and come to speed with them.

Regards

**Comment by cherrera2001** [comment]
Its in the root of dev.


On June 20, 2018 at 10:09:02 AM, SPParnerkar (notifications@github.com)
wrote:

Chris,

Can you please attach Jenkinsfile and/or any other artefact you have with
respect to this and #459 <https://github.com/hashmapinc/Tempus/issues/459>.
I will review and come to speed with them.

Regards

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/hashmapinc/Tempus/issues/459#issuecomment-398786218>,
or mute the thread

**Comment by SPParnerkar** [comment]
Created a simple pipeline to build Tempus from local clone. Currently it fails at Tempus-Server-Core-Extensions with message:

Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project extensions-core: An error occurred while invoking protoc. Error while executing process. Cannot run program "/var/lib/jenkins/workspace/Tempus/extensions-core/target/protoc-plugins/protoc-3.0.2-linux-x86_64.exe": error=2, No such file or directory -> [Help 1]

Build succeeds from command line.

**Comment by SPParnerkar** [comment]
F
