### ISSUE TITLE
Customer user gets error while accessing Tempusboard

### ISSUE THREAD

**Issue by jayeshkapadnis** [hashmapinc/Tempus#519]
1. Login as a Customer user.
2. Click on TempusBoard from Sidebar menu
3. Gets an Access Forbidden Alert.

Screenshot attached

**Comment by jayeshkapadnis** [comment]
![Screen Shot 2018-07-05 at 4.47.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca501d3d86480012a8879f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246454f66b7191a37cf1162c4f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd96c0e7c903d43a9b18b4eb901ba21d91b80e5ed8d1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df54be6455ca7173f63ef7f2431.png)

**Comment by SPParnerkar** [comment]
We have removed TempusBoard link from sidebar and this situation will not arise in future. Closing the issue.
