### ISSUE TITLE
Put some credits to ThingsBoard project

### ISSUE THREAD

**Issue by ashvayka** [hashmapinc/Tempus#637]
Look at https://www.apache.org/licenses/LICENSE-2.0 Item 4. Redistribution

**Comment by cherrera2001** [comment]
@jayeshkapadnis can we action this immediately. @ashvayka thanks for the notification, this certainly was not on purpose, our ci system modified the license template. It will be addressed ASAP!

**Comment by jayeshkapadnis** [comment]
Working on it right away..

**Comment by cherrera2001** [comment]
Done as part of #638

**Comment by ashvayka** [comment]
@cherrera2001 thanks!
