### ISSUE TITLE
Create and document a WITSML flow to Tempus

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#66]
_From @cherrera2001 on January 2, 2018 20:5_

Create and document a WITSML flow that receives log and trajectory data from a witsml server. The thingsboard device that the WITSML data is published to should act as a gateway and create a new device per well.

_Copied from original issue: hashmapinc/Timeseries#106_

**Comment by shubhamkumargupta** [comment]
Written the Google document for explaining the flow and configuring the Nifi Processor to publish data to thingsboard gateway topic.
Google Document Link : https://docs.google.com/document/d/1Xwn3xGBYzbBWcaeAp5SSATQ-nMv9A7xwdhC4EX4V6AI/edit?usp=sharing
