### ISSUE TITLE
Open side nav for an asset click present on the asset list in asset landing widget

### ISSUE THREAD

**Issue by Himanshu-it** [hashmapinc/Tempus#673]
child of #635

**Comment by SPParnerkar** [comment]
This function has been replaced by functionality described at  https://drive.google.com/open?id=1pNhi2Hq3LM0dsPvIqRm_fCfK3Ym1mSzmDkw6rEl5COM&usp=gmail

**Comment by SPParnerkar** [comment]
This task has been merged with #671. Closing the issue.
