### ISSUE TITLE
As a User, I would like assign devices to assets created in landing page*

### ISSUE THREAD

**Issue by SPParnerkar** [hashmapinc/Tempus#698]
Child of #578 

A user would like to assign devices to assets, which were created from asset landing page. Device assignment process will be as follows:

1. User (or Tenant Admin) adds a device
2. If Tenant Admin assigns the device to a BU.  A User can only assign to their home BU.
3. User (or Tenant Admin) add **Server Side Device Attributes**.
4. User (or Tenant Admin) use **Relations** tab to create an Outbound Relations of type 'Contains' to an Entity. The Entity type will be the lowest level of Data Model Object, which is attached to that BU. and values will be all assets, which were created using the Asset Landing Page of that Data Model Object.

For example, if a BU has a Data Model with **Fields, Rigs and Wells** as Data Model Objects. The **Entity  Type** in this case will be a **Well** and List of values will be all the Wells added for that BU.

*This is a quick fix for the demo purpose only and not a permanent feature. The complete feature "Device Mapping to BU Data Model' is yet to be finalized.

**Comment by akshaymhetre** [comment]
Depends on #791
