### ISSUE TITLE
Cannot create asset

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#708]
Cannot create asset as tenant admin, says unauthorized

**Comment by shubhamkumargupta** [comment]
Hi @cherrera2001, this was the issue before completion of Group feature. Its working fine now, you need to take latest branch of HAF and Tempus. It will work fine after that, if still you face any issue let me know I'll look into this.

**Comment by niaalex** [comment]
Tested works fine @shubhamkumargupta  will close now
