### ISSUE TITLE
Data Model attribute duplicate name

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Tempus#796]
Child of #810
While creating a data model, I gave several of the objects the attribute name and other different attributes.  I was able to create the assets and devices and everything looked ok on the screen, but when I saved the data model it saved, but threw an error pop up about duplicate object or something similar (I didn't think to copy the exact wording at the time).

When I went to another part of tempus and then tried to go back to the data model, a few of the assets did not appear and the relationships were not present.  So it appears the data model is corrupted.

The name of the corrupted data model is "Drilling Onshore" on the current live demo tempus.hashmapinc.com environment.

**Comment by Shobhit2884** [comment]
This is issue is fixed at tempus.hashmap.inc.com, latest code has been deployed, please make sure whenever you make any changes in datamodel screen click on  the tick mark to save the changes.

**Comment by niaalex** [comment]
@Mike-d-s  please confirm this

**Comment by Mike-d-s** [comment]
Tried to break it again, but couldn't.  I couldn't create objects with the same name or break the model with different attributes with the same name.  So seems to be fixed.

**Comment by niaalex** [comment]
Thanks for the update

Did you move it to DONE or should I?

**Comment by niaalex** [comment]
Thanks @Mike-d-s  I have moved it to DONE
