### ISSUE TITLE
Test isValid flag when a rule is deleted and there are more than 1 rules in an app

### ISSUE THREAD

**Issue by ganeshx** [hashmapinc/Tempus#87]

**Comment by jetinder20** [comment]
Is there an error you are facing while doing that? The way i have coded, it should not matter as I retrieve an application associated with a deleted rule and invalidate that.

**Comment by jetinder20** [comment]
This need to be discussed more. I plan to discuss this with ganesh in person when i am in Atlanta and work on it.
