### ISSUE TITLE
Get all the application names associate with list of rule Id's

### ISSUE THREAD

**Issue by ganeshx** [hashmapinc/Tempus#88]

**Comment by jetinder20** [comment]
The API to fetch application names for a rule id is already in place. I assume this is used to show a warning before a rule is deleted. From current UI, We can only delete one rule at a time(Or i am wrong here?) so the current API should be sufficient, right ?

**Comment by jetinder20** [comment]
Changes have been pushed on branch "tempus-27-application-computation-linking". The same endpoint now takes an array
