### ISSUE TITLE
As system admin on clicking on Plugin and Rule tab Invalid UUID  Error message is coming

### ISSUE THREAD

**Issue by shubhamkumargupta** [hashmapinc/Tempus#911]
Child of #929

As system admin on clicking on Plugin and Rules tab, an Invalid UUID  Error message is coming

![screenshot from 2018-12-05 11-29-00](https://user-images.githubusercontent.com/13195909/49493371-e0c0c700-f881-11e8-97f9-06045015517d.png)

**Comment by NandiniMGawade** [comment]
Completed
