### ISSUE TITLE
As system admin, Access Forbiden error coming on creating new Widget

### ISSUE THREAD

**Issue by shubhamkumargupta** [hashmapinc/Tempus#912]
Child of #929

As a system admin, Access Forbidden error coming on creating new Widget
![screenshot from 2018-12-05 11-36-40](https://user-images.githubusercontent.com/13195909/49493518-70667580-f882-11e8-8ba3-b35bbadd06ef.png)

Also, as Tenant Login, Invalid UUID error message on clicking on Cards Widget
![screenshot from 2018-12-05 11-44-51](https://user-images.githubusercontent.com/13195909/49493732-35187680-f883-11e8-81a6-8eab037f3614.png)

**Comment by NandiniMGawade** [comment]
Completed
