### ISSUE TITLE
Spike: AWS Lambda

### ISSUE THREAD

**Issue by XxChauhanxX** [hashmapinc/Tempus#961]
Child of #952

The spike is to check the overall scope and feasibility of adding AWS Lambda for Computations. 

The outcome of the spike would be:

**Comment by akshaymhetre** [comment]
Explore following things:

1. Writing basic lambda function and running it locally using SAML: https://github.com/akshaymhetre/AWSLambdaSample

2. Tried function deployment from console and from JAVA sdk as well. 
 - sdk : https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-lambda

3. Tried API to list uploaded lambda functions, describing functions and delete using sdk.

4. Triggers: 
 - kafka triggers are not provided by AWS. One can implement in the lambda function itself or write own kafka connect custom sink app to push data to lambda function

**Comment by shgupta22** [comment]
Explored the following things:

1. Writing Java HelloWorld Lambda Function: https://github.com/shubhamkumargupta/lambdaexample

2. Writing Java Program to deploy, list, invoke Lambda Function using AWS-SDK: https://github.com/shubhamkumargupta/deploy-lambda

3.  CLI Lambda command to create new lambda function : aws lambda create-function --function-name CliLambda --runtime java8 --role arn:aws:iam::660239660726:role/name --handler example.Hello::myHandler  --zip-file "fileb://lambdaexample.zip"

4. Some useful links : 
- Packaging Zip: https://docs.aws.amazon.com/lambda/latest/dg/create-deployment-pkg-zip-java.html
- Sample Program: https://www.baeldung.com/java-aws-lambda
- AWS SDK: https://github.com/aws/aws-sdk-java
- CLI Create API: https://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html
- Create a Lambda Function using Java: https://www.testingexcellence.com/invoke-test-aws-lambda-function-locally-java
- AWS Lambda Events: https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events
