### ISSUE TITLE
Fetching Gateway Devices API not working on Agent tab while Tenant Login

### ISSUE THREAD

**Issue by shubhamkumargupta** [hashmapinc/Tempus#971]
Due to change in Pagination API's for devices, get gateway devices API is breaking on Agent Tab on Tenant Login. There is a need to change the API call for fetching Gateway devices.
![screenshot from 2019-01-03 14-56-28](https://user-images.githubusercontent.com/13195909/50631024-e2f17080-0f68-11e9-9a89-2665188735e3.png)

Grid View on Device tab, not able to load devices more than 30. Resolve this by implementing autoscrolling on grid view.

**Comment by NandiniMGawade** [comment]
Merged into dev.
