### ISSUE TITLE
SPIKE: Database Versioning

### ISSUE THREAD

**Issue by XxChauhanxX** [hashmapinc/Tempus#988]
Child of #981

**Comment by akshaymhetre** [comment]
Different versioning tools, pros and cons

Flyway : 

- Pros: 
    - you can provide migration scripts not only in SQL format but also as Java code
	- commands can be executed from the command line, from a build process (e.g. with Maven or Gradle) or directly from Java code, using the API
	- 6 commands : migrate-executes script if not applied, info- currently available migration scripts, validate- check if migration will work or not, repair, clean
 - cons:
        - rollback is paid
        - Tightly couple with SQL

Liquibase:
	- Pros:
		- Decouples db refactoring process from underlying db technologies. Defines change in changelog xml/json/yaml
	- Cons:
    		- Writing xml/json change log is a pain for strong SQL based application 		



Flyway :

- Migrations can be either versioned or repeatable

The file name consists of the following parts:
* Prefix: V for versioned (configurable), U for undo (configurable) and R for repeatable migrations (configurable)
* Version: Version with dots or underscores separate as many parts as you like (Not for repeatable migrations)
* Separator: __ (two underscores) (configurable)
* Description: Underscores or spaces separate the words
* Suffix: .sql (configurable)

- Resources/db/migration
- Flyway adds a special schema history table to your schema. You can think of this table as a complete audit trail of all changes performed against the schema.
- You can attach callbacks beforeMIgrate, beforeUndo
- Flyway Pro gives dry run feature
- Placeholder feature in SQL {} can be provided though maven
- Many plugins available to integrate with CI 

Sample Code  : https://github.com/akshaymhetre/flywayDBSample

**Comment by anuj-akt** [comment]
We already have implemented logic for schema upgrade in Tempus. If there are some issues in schema upgrade flow we will fix it. We are not moving to Flyway as version rollback feature is available in paid version.

Closing this issue for now.
