### ISSUE TITLE
SPIKE: UI Guide for Freemium user

### ISSUE THREAD

**Issue by XxChauhanxX** [hashmapinc/Tempus#997]
Child of #994
As a Product Owner I want a user guide on Tempus, which would prompt a new user to take actions in Tempus, so that the user can navigate and use through Tempus.

Some of the standard practices to consider while implementing the UI guide: 
-> Hierarchy. Set a clear hierarchy on the screen. One thing should clearly be the most important (i.e. larger, more colorful). If other things are on the screen, then they should clearly be less important (i.e. less contrast, less space around them). A lot of design mistakes can be cleared up by answering "What is the most important thing here? What is second and third?"
-> Colors. Start with one color plus light and dark grey. Add another color if you want to. You could add a third, but more than three colors is usually unnecessary. Two-to-six shades of light and dark grey will usually be enough. Avoid shades of grey in the middle range.
-> Typography. Establish a clear size hierarchy. As a rule of thumb, have three basic sizes: headline, title, and body (regular) size. The font-size menus in word processors show certain numbers (18, 36, 64 etc.) because their ratios go well together, so that is a good place to pick from.
Iconography. Icons should generally be a muted single-color (gray, faded colors) and not be too eye-catching unless they are actions or meant to draw attention.
-> Spacing. Make sure you to tighten up spacing of elements. Spacing on the top and bottom should be consistent. Pay attention to proper spacing between elements as well.
-> Alignment. Make sure elements are aligned to a grid. In other words, each view should be aligned to surrounding elements (i.e text to the middle or edge of an image). Here is a useful exercise: Pick the left edge of any object in a design. Now draw a vertical line from the top to the bottom of the screen, aligned with that edge. Now do that for every element on screen, unless it already rests on a line. How many lines do you end up with? Try to reduce that number by aligning elements to the same vertical lines.
-> Information. Present only the information that is necessary in a given moment. Having multiple pieces of text that are all near each other, or several items that are exactly the same size color and style, is usually not a good practice.
Tabs. Tabs should be a consistent with the background color of the Toolbar above them.

**Comment by XxChauhanxX** [comment]
Need to discuss the implementation of it, when should this be done. Since there is plan to upgrade the overall UI/UX for Tempus along with upgrade to Angular 6

**Comment by Shobhit2884** [comment]
Shepherd Tool For user guide is an extensive library for creating a tour guide for  the applications.

Dependency needed :- Tippy.JS for animations.
Installation Command:- npm install shepherd.js --save

Import the library into your code and create a tour by adding an array of steps .
Following is the Documentation link which gives the API resource:-
https://shipshapecode.github.io/shepherd/

Shepherd also provide wrapper code for angular named angular-shepherd, you can find the github repo here:- 
https://github.com/shipshapecode/angular-shepherd ( Compatible to Angular 6 and 7), apart from that they also provide wrappers for ember,recat and vuejs.

 Additional Link for steps describing the usage:-
https://code.tutsplus.com/tutorials/how-to-build-a-user-tour-with-shepherd-in-javascript--cms-28509
